{{- if .Values.immich.configuration }}
apiVersion: v1
{{- if .Values.immich.storeConfigInSecret }}
kind: Secret
{{- else }}
kind: ConfigMap
{{- end }}
metadata:
  name: {{ .Release.Name }}-immich-config
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ printf "%s-%s\n" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- if .Values.immich.storeConfigInSecret }}
type: Opaque
stringData:
{{- else }}
data:
{{- end }}
  immich-config.yaml: |
{{- .Values.immich.configuration | toYaml | nindent 4 }}
{{- end }}
