{{- if and (.Values.immich.valkey.auth.enabled) (not .Values.immich.valkey.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-valkey-auth" .Release.Name }}
type: Opaque
data:
  REDIS_PASSWORD: {{ include "valkey.password" . | b64enc }}
{{- end }}
