---
apiVersion: v2
description: A chart to power Immich (immich.app) running on kubernetes
name: immich
version: 0.9.7
home: https://immich.app/
icon: https://raw.githubusercontent.com/immich-app/immich/main/design/immich-logo.svg
sources:
  - https://github.com/immich-app/immich-charts/tree/main/charts/immich
  - https://github.com/immich-app/immich
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 1.5.1
  - name: postgresql
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 16.7.13
  - name: redis
    condition: redis.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 20.13.4
annotations:
  artifacthub.io/category: storage
  artifacthub.io/changes: |-
    - kind: changed
      description: Check the Release Notes on GitHub
      links:
        - name: Release Notes
          url: https://github.com/maybeanerd/immich-charts/releases
