---
apiVersion: v2
description: A chart to power Immich (immich.app) running on kubernetes
name: immich
version: 0.10.1
appVersion: v2.1.0
home: https://immich.app/
icon: https://raw.githubusercontent.com/immich-app/immich/main/design/immich-logo.svg
sources:
  - https://github.com/immich-app/immich-charts/tree/main/charts/immich
  - https://github.com/immich-app/immich
maintainers:
  - name: PixelJonas
    email: 5434875+PixelJonas@users.noreply.github.com
  - name: bo0tzz
    email: immich@bo0tzz.me
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.3.0
annotations:
  artifacthub.io/category: storage
  artifacthub.io/changes: |-
    - kind: removed
      description: Breaking changes
      links:
        - name: Release notes
          url: https://github.com/immich-app/immich-charts/releases/tag/immich-0.10.0
    - kind: removed
      description: Postgres subchart
    - kind: removed
      description: Redis subchart
    - kind: changed
      description: Common library dependency update
