name: pull-request-validation

on:
  pull_request:

jobs:
  build_lint_validate_diff:
    name: lint, validate and diff from main
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: alpine/helm:3.19.0@sha256:aef9b56f64e866207d9591d0abd8f6d767b36aadd12edf68f8a719716d9d29c9
    steps:
      - name: checkout pr head
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - name: install chart dependencies
        run: helm dependency build charts/immich

      - name: lint helm chart
        run: helm lint charts/immich --set immich.persistence.library.existingClaim=test-pvc --set valkey.enabled=true

      - name: prepare
        run: mkdir -p charts/immich/build
      - name: create full manifest from pr head
        run: helm template immich charts/immich --set immich.persistence.library.existingClaim=test-pvc --set valkey.enabled=true | tee charts/immich/build/manifest.yaml

      - name: checkout main
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
          ref: main
          path: main

      - name: install chart dependencies
        run: helm dependency build main/charts/immich

      - name: prepare
        run: mkdir -p main/charts/immich/build
      - name: create full manifest from main
        run: helm template immich main/charts/immich --set immich.persistence.library.existingClaim=test-pvc --set valkey.enabled=true | tee main/charts/immich/build/manifest.yaml

      - name: create diff comment
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: int128/diff-action@ddd48b26efc80cbca9139353926ac2ec214e08e6 # v2.2.0
        with:
          base: main/charts/immich/build
          head: charts/immich/build
          comment-header: "## Changes in Final Manifest"

  tilt_validation:
    name: Validate Tilt deployment and server startup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@cd24790a7f5f6439ac32cc94f5523cb2de8bfa8c # use-mise-action-v1.1.0

      - name: Run Tilt CI validation
        run: mise run local:ci
