name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: get latest release
        id: version
        run: |
          tag=$(curl -s https://api.github.com/repos/immich-app/immich-charts/releases/latest | jq '.tag_name' -r)
          chart_version=$(yq '.version' charts/immich/Chart.yaml)
          if [[ "$chart_version" != "${tag#immich-}" ]]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate a token
        id: generate-token
        if: ${{ steps.version.outputs.should_release == 'true' }}
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        with:
          app-id: ${{ secrets.PUSH_O_MATIC_APP_ID }}
          private-key: ${{ secrets.PUSH_O_MATIC_APP_KEY }}
      
      - name: run chart-releaser
        id: cr
        if: ${{ steps.version.outputs.should_release == 'true' }}
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        env:
          CR_TOKEN: ${{ steps.generate-token.outputs.token }}
          CR_GENERATE_RELEASE_NOTES: true
          CR_SKIP_EXISTING: true

      - name: Login to GitHub Container Registry
        if: ${{ steps.version.outputs.should_release == 'true' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ steps.version.outputs.should_release == 'true' }}
        name: Push Chart
        run: helm push .cr-release-packages/immich-*.tgz oci://ghcr.io/${{ github.repository }}
